### ISSUE TITLE
Alterar estágio da oportunidade quando trocar o time de venda. 

### ISSUE THREAD

**Issue by eduaparicio** [Escodoo/crm-addons#2]
Ao trocar a equipe de vendas de uma oportunidade, caso cada equipe tenha o seu próprio funil, o estágio atual é mantido e passa a ser exibido no outro funil, da nova equipe de vendas

Para testar o comportamento, siga os passos:

1. Defina estágios específicos por equipe de vendas
2. Crie uma oportunidade para a equipe de vendas 1
3. Edite a oportunidade e troque a equipe de vendas para 2
4. Perceba que o estágio específico da 1 foi mantido e passa a ser exibido no funil da equipe 2

**Comment by marcelsavegnago** [comment]
@eduaparicio Esse comportamento é padrão do sistema. Após efetuar a mudança do time responsável pela oportunidade é necessário trocar o estágio também.
